name: upload_download_test
on: [push]
jobs:
  download-job:
    runs-on: ubuntu-18.04
    name: Download file
    steps:
      - name: Download a artifact
        uses: actions/download-artifact@v2
      - name: list pwd
        run: pwd
      - name: list file
        run: ls
      - name: load file
        run: cat my_upload_download.txt

        