name: upload_download_test
on: [push]
jobs:
  upload-job:
    runs-on: ubuntu-18.04
    name: Save file
    steps:
      - name: list pwd
        run: pwd
      - name: create file
        run: echo "this is bertramoon's test" >> my_upload_download.txt
      - name: Upload my_upload_download.txt
        uses: actions/upload-artifact@v2
        with:
          name: my_upload_download
          path: my_upload_download.txt
  download-job:
    runs-on: ubuntu-18.04
    name: Download file
    needs: upload-job
    steps:
      - name: Download a artifact
        uses: actions/download-artifact@v2
        with:
          name: my_upload_download
      - name: list pwd
        run: pwd
      - name: list file
        run: ls

        