name: upload_download_test
on: [push]
jobs:
  download-job:
    runs-on: ubuntu-18.04
    name: Download file
    steps:
      - name: Download a file
        runs-on: wget https://github.com/Bertramoon/actions_test/suites/5456169330/artifacts/173517005
      - name: list pwd
        run: pwd
      - name: list file
        run: ls

        